/**
 * Binds this package's decorators to the TypeSpec compiler.
 *
 * `lib/main.tsp` imports this file's `$decorators` export, matching each
 * `extern dec` to its implementation.
 */

import {
  $asyncTag,
  $binding,
  $kafkaChannel,
  $kafkaMessage,
  $kafkaOperation,
  $amqpChannel,
  $anypointMqChannel,
  $anypointMqMessage,
  $ibmMqChannel,
  $ibmMqMessage,
  $ibmMqServer,
  $jmsChannel,
  $jmsMessage,
  $jmsServer,
  $solaceOperation,
  $solaceServer,
  $googlePubSubChannel,
  $googlePubSubMessage,
  $natsOperation,
  $pulsarChannel,
  $pulsarServer,
  $sqsChannel,
  $sqsOperation,
  $amqpMessage,
  $amqpOperation,
  $httpMessage,
  $httpOperation,
  $kafkaServer,
  $mqttMessage,
  $mqttOperation,
  $mqttServer,
  $websocketChannel,
  $channel,
  $contentType,
  $correlationId,
  $dynamicChannel,
  $extension,
  $externalDocs,
  $header,
  $headers,
  $info,
  $jsonSchemaExtension,
  $message,
  $messageExample,
  $oneOf,
  $parameterLocation,
  $rawHeaders,
  $rawPayload,
  $receive,
  $replyAddress,
  $replyChannel,
  $securityScheme,
  $send,
  $server,
  $useSecurity,
  $useServer,
} from "./decorators/index.js";

export { $lib } from "./lib.js";
// The compiler binds this from here, and it runs on every compilation that
// loads the library rather than only on one that asks for a document.
export { $onValidate } from "./validate.js";

/**
 * The decorator implementations, for the compiler rather than for a
 * consumer of this package. Keeping the binding here, and out of
 * `src/index.ts`, makes the published API a decision, not a side effect of
 * which file happens to export what.
 *
 * @internal
 */
export const $decorators = {
  AsyncAPI: {
    info: $info,
    server: $server,
    securityScheme: $securityScheme,
    useSecurity: $useSecurity,
    externalDocs: $externalDocs,
    asyncTag: $asyncTag,
    oneOf: $oneOf,
    jsonSchemaExtension: $jsonSchemaExtension,
    extension: $extension,
    message: $message,
    contentType: $contentType,
    header: $header,
    headers: $headers,
    rawPayload: $rawPayload,
    rawHeaders: $rawHeaders,
    correlationId: $correlationId,
    messageExample: $messageExample,
    channel: $channel,
    dynamicChannel: $dynamicChannel,
    useServer: $useServer,
    parameterLocation: $parameterLocation,
    send: $send,
    receive: $receive,
    replyChannel: $replyChannel,
    replyAddress: $replyAddress,
    binding: $binding,
    kafkaServer: $kafkaServer,
    kafkaChannel: $kafkaChannel,
    kafkaOperation: $kafkaOperation,
    kafkaMessage: $kafkaMessage,
    websocketChannel: $websocketChannel,
    mqttServer: $mqttServer,
    mqttOperation: $mqttOperation,
    mqttMessage: $mqttMessage,
    httpOperation: $httpOperation,
    httpMessage: $httpMessage,
    amqpChannel: $amqpChannel,
    amqpOperation: $amqpOperation,
    amqpMessage: $amqpMessage,
    natsOperation: $natsOperation,
    pulsarServer: $pulsarServer,
    pulsarChannel: $pulsarChannel,
    googlePubSubChannel: $googlePubSubChannel,
    googlePubSubMessage: $googlePubSubMessage,
    sqsChannel: $sqsChannel,
    sqsOperation: $sqsOperation,
    anypointMqChannel: $anypointMqChannel,
    anypointMqMessage: $anypointMqMessage,
    jmsServer: $jmsServer,
    jmsChannel: $jmsChannel,
    jmsMessage: $jmsMessage,
    ibmMqServer: $ibmMqServer,
    ibmMqChannel: $ibmMqChannel,
    ibmMqMessage: $ibmMqMessage,
    solaceServer: $solaceServer,
    solaceOperation: $solaceOperation,
  },
};
